[target.'cfg(any(all(target_env = "gnu", not(target_os = "windows")), target_os = "freebsd"))']
rustflags = [
  "-C",
  "link-args=-Wl,--warn-unresolved-symbols",
  "-C",
  "link-args=-Wl,-z,nodelete",
]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static", "-C","link-args=-ladvapi32"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
